---
driver:
  name: docker
  hostname: haproxy.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: haproxy
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - haproxy
  pillars:
    top.sls:
      base:
        "*":
          - haproxy

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: admin
    provisioner:
      pillars-from-files:
        haproxy.sls: tests/pillar/admin.sls

  - name: single_contrail
    provisioner:
      pillars-from-files:
        haproxy.sls: tests/pillar/single_contrail.sls

  - name: single_general_service
    provisioner:
      pillars-from-files:
        haproxy.sls: tests/pillar/single_general_service.sls

  - name: single_mysql_service
    provisioner:
      state_top:
        base:
          "*":
            - galera
            - haproxy
      pillars:
        top.sls:
          base:
            "*":
              - galera
              - haproxy
      pillars-from-files:
        haproxy.sls: tests/pillar/single_mysql_service.sls

  - name: single_openstack_service
    provisioner:
      pillars-from-files:
        haproxy.sls: tests/pillar/single_openstack_service.sls

  - name: stats
    provisioner:
      pillars-from-files:
        haproxy.sls: tests/pillar/stats.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
